<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KORIX_Tweaks</AssemblyName>
    <RootNamespace>KORIX_Tweaks</RootNamespace>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>assets\KORIX.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <Resource Include="assets\KORIX-rounded.png" />
  </ItemGroup>
</Project>